query($comment_id: ID!, $path: String!) {
    comment: comment(id: $comment_id) {
        author {
            id
            account
            avatarImage {
                url
            }
            url
        }
        id
        publishedAt
        summary: contentSummaryHtml
    }
    to_note: noteFromPath(path: $path) {
        id
        title
    }
}
